version: '3.8'

services:
  litellm:
    environment:
      - LITELLM_MASTER_KEY=dev-master-key-12345
      - LITELLM_LOG_LEVEL=DEBUG
      - LITELLM_CONFIG_PATH=/app/config.yaml
    volumes:
      - ./litellm-config.dev.yaml:/app/config.yaml:ro

  caddy:
    ports:
      - "8080:8080"
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config 
