router_mode: true
default_model: gpt-3.5-turbo

model_list:
  # OpenAI Models
  - model_name: gpt-3.5-turbo
    litellm_provider: openai
    api_key: os.environ/OPENAI_API_KEY
  
  - model_name: gpt-4
    litellm_provider: openai
    api_key: os.environ/OPENAI_API_KEY
  
  - model_name: gpt-4-turbo
    litellm_provider: openai
    api_key: os.environ/OPENAI_API_KEY

  # Anthropic Models
  - model_name: claude-3-haiku
    litellm_provider: anthropic
    api_key: os.environ/ANTHROPIC_API_KEY
  
  - model_name: claude-3-sonnet
    litellm_provider: anthropic
    api_key: os.environ/ANTHROPIC_API_KEY

  # Ollama (when available)
  # - model_name: ollama/llama3
  #   litellm_provider: ollama
  #   api_base: http://ollama:11434

# Rate limiting and security
general_settings:
  completion_model: gpt-3.5-turbo
  max_tokens: 4096
  
# API Key management for client access
litellm_settings:
  success_callback: ["prometheus"]
  failure_callback: ["prometheus"]
  set_verbose: true 
